import React from 'react'
import ReactDOM from 'react-dom/client'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'

const README_MARKDOWN = `
# gitignore.in

.gitignore generator for your project

Website: https://gitignore.in/

Repository: https://github.com/gitignore-in/gitignore-in

## Concept

gitignore.in is a tool to generate .gitignore files for your projects.
\`.gitignore.in\` file stores the target of [gibo](https://github.com/simonwhitaker/gibo) and [gitignore.io](https://www.toptal.com/developers/gitignore/). You can generate a .gitignore file by running the gitignore.in command.

![generate .gitignore from .gitignore.in](./concept.png)

## Installation

### Binary Releases

Download the binary from the releases page https://github.com/gitignore-in/gitignore-in/releases

And place it in a directory that is in the \`PATH\`.

### Homebrew (macOS)

You can install gitignore-in using the Homebrew package manager.

\`\`\`
$ brew tap gitignore-in/gitignore-in
$ brew install gitignore-in
\`\`\`

## Usage

\`\`\`bash
$ gitignore.in --help
\`\`\`

\`\`\`
$ gitignore.in
\`\`\`

This generates \`.gitignore.in\` if needed and rebuilds \`.gitignore\`.
If \`.gitignore.in\` does not exist but \`.gitignore\` already exists, gitignore.in first infers a starting \`.gitignore.in\` and then rebuilds \`.gitignore\`.

Write the template you want to use in \`.gitignore.in\`, like shell script:

\`\`\`bash
$ cat .gitignore.in
# This is a comment
gibo dump Linux
gibo dump macOS
gibo dump Windows
gibo dump Python
echo '.coverage'
echo '.env'
\`\`\`

Running \`gitignore.in\` again updates \`.gitignore\`.

If you already have a \`.gitignore\`, you can infer a starting \`.gitignore.in\` from it:

\`\`\`bash
$ gitignore.in infer --gibo Rust,macOS --gi node
\`\`\`

This infer mode is heuristic.
It tries to cover the existing \`.gitignore\` with the specified \`gibo dump ...\` and \`gi ...\` candidates, then falls back to \`echo '...'\` for unmatched lines.
If you omit both \`--gibo\` and \`--gi\`, it checks all available templates from both providers.

Search available templates before adding them:

\`\`\`bash
$ gitignore.in search macos rust
\`\`\`

This matches template names case-insensitively by substring.

Add templates without worrying about \`gibo\` vs \`gi\`:

\`\`\`bash
$ gitignore.in add rust macos node
\`\`\`

\`gitignore.in\` resolves names case-insensitively, prefers the provider already used in \`.gitignore.in\`, and rebuilds \`.gitignore\` after the update.

Remove templates in the same way:

\`\`\`bash
$ gitignore.in remove RUST Node
\`\`\`

If the \`.gitignore\` was already generated by \`gitignore.in\`, you can restore \`.gitignore.in\` from its embedded section headers:

\`\`\`bash
$ gitignore.in restore
\`\`\`

## CLI behavior

\`gitignore.in\` follows common POSIX CLI conventions. The notes below summarize
what callers and automation scripts can rely on.

### Exit code

- \`0\` on success.
- Non-zero on any error (invalid argument, unknown template, network failure,
  file I/O failure, etc.).

### Streams

- \`stdout\`: generated content, status lines (e.g. \`Generated .gitignore\`),
  and \`search\` results (one \`<provider>\\t<name>\` row per match).
- \`stderr\`: argument-parsing errors and the final error message of a failed
  run.

### Help and version

Run \`gitignore.in --help\` (or \`-h\`) for top-level help, or
\`gitignore.in <subcommand> --help\` for per-subcommand help. The installed
version is printed by \`gitignore.in --version\` (or \`-V\`).

### Subcommands

| subcommand        | summary                                                                              |
| ----------------- | ------------------------------------------------------------------------------------ |
| _(none)_          | Bootstrap \`.gitignore.in\` if needed and rebuild \`.gitignore\`                         |
| \`infer\`           | Infer a starting \`.gitignore.in\` from an existing \`.gitignore\` and rebuild \`.gitignore\` |
| \`search <terms>\`  | Search templates available from gibo and gitignore.io                                |
| \`add <names>\`     | Add templates to \`.gitignore.in\` and rebuild \`.gitignore\`                            |
| \`remove <names>\`  | Remove templates from \`.gitignore.in\` and rebuild \`.gitignore\`                       |
| \`restore\`         | Restore \`.gitignore.in\` from a generated \`.gitignore\` and rebuild \`.gitignore\`       |

### Template name matching

For \`search\`, \`add\`, and \`remove\`, template names (\`Rust\`, \`macOS\`, \`node\`,
…) are matched **case-insensitively**, so \`add rust macos node\` and
\`remove RUST Node\` behave the same as their canonical-case variants.

`

export default function Home() {
  return (
    <ReactMarkdown remarkPlugins={[remarkGfm]}>{README_MARKDOWN}</ReactMarkdown>
  )
}

// biome-ignore lint/style/noNonNullAssertion: root must be present in the document
const mountTo = document.getElementById('root')!

ReactDOM.createRoot(mountTo).render(
  <React.StrictMode>
    <Home />
  </React.StrictMode>,
)
