name: test
on:
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest

    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.11

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check all
        run: bun run lint

      - name: Build
        run: bun run build

      - name: Install Cypress binary
        run: bun x cypress install

      - name: E2E Test
        uses: cypress-io/github-action@v5
        with:
          build: bun run build
          start: bun run dev
